"""ProductPulse AI - Streamlit dashboard for product review analysis.

Run with:  streamlit run app.py
"""

from __future__ import annotations

import hashlib
import io

import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

import ai_service
from data_loader import load_reviews
from sentiment import add_sentiment, sentiment_counts
from themes import top_complaints

SENTIMENT_COLORS = {"Positive": "#16a34a", "Neutral": "#64748b", "Negative": "#dc2626"}
ALL_PRODUCTS = "All products"


@st.cache_data(show_spinner=False)
def load_and_score(file_bytes: bytes | None, file_name: str | None) -> dict:
    """Load the uploaded CSV (or the bundled sample) and add VADER sentiment. Cached per file."""
    source = None
    if file_bytes is not None:
        source = io.BytesIO(file_bytes)
        source.name = file_name
    loaded = load_reviews(source)
    loaded["dataframe"] = add_sentiment(loaded["dataframe"])
    return loaded


@st.cache_data(show_spinner=False, ttl=3600)
def cached_summary(reviews: pd.DataFrame, subject: str, model: str) -> dict:
    """Cache AI summaries so re-running the page does not repeat paid API calls."""
    return ai_service.generate_review_summary(reviews, subject)


def draw_sentiment_chart(counts: pd.Series) -> None:
    """Bar chart of Positive / Neutral / Negative review counts."""
    fig, ax = plt.subplots(figsize=(6.4, 3.4))
    values = [int(v) for v in counts.values]
    bars = ax.bar(counts.index, values, color=[SENTIMENT_COLORS[k] for k in counts.index], width=0.6)
    ax.set_ylabel("Reviews")
    ax.spines[["top", "right"]].set_visible(False)
    ax.set_ylim(0, max(values + [1]) * 1.2)
    ax.bar_label(bars, padding=3)
    fig.tight_layout()
    st.pyplot(fig, clear_figure=True)
    plt.close(fig)


def filter_reviews(df: pd.DataFrame, product: str, date_range: tuple) -> pd.DataFrame:
    """Apply the sidebar product and date filters."""
    view = df
    if product != ALL_PRODUCTS:
        view = view[view["product_name"] == product]
    if len(date_range) == 2:
        start, end = (pd.Timestamp(d) for d in date_range)
        view = view[(view["review_date"] >= start) & (view["review_date"] < end + pd.Timedelta(days=1))]
    return view


def search_reviews(df: pd.DataFrame, query: str, sentiment: str) -> pd.DataFrame:
    """Filter the review table by sentiment and a free-text search."""
    view = df if sentiment == "All" else df[df["sentiment"] == sentiment]
    needle = query.strip()
    if needle:
        mask = (
            view["review_text"].str.contains(needle, case=False, regex=False)
            | view["product_name"].str.contains(needle, case=False, regex=False)
            | view["review_id"].str.contains(needle, case=False, regex=False)
        )
        view = view[mask]
    return view


def review_table(df: pd.DataFrame) -> pd.DataFrame:
    """Columns shown wherever reviews are listed."""
    table = df[["review_id", "product_name", "rating", "sentiment", "sentiment_score", "review_date", "review_text"]].copy()
    table["review_date"] = table["review_date"].dt.strftime("%Y-%m-%d")
    table["sentiment_score"] = table["sentiment_score"].round(3)
    return table


def render_overview(df: pd.DataFrame) -> None:
    total = len(df)
    counts = sentiment_counts(df)
    share = lambda n: f"{n / total * 100:.0f}% of reviews" if total else None  # noqa: E731

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total reviews", total)
    c2.metric("Average rating", f"{df['rating'].mean():.2f} / 5" if total else "-")
    c3.metric("Positive reviews", int(counts["Positive"]), share(counts["Positive"]), delta_color="off")
    c4.metric("Negative reviews", int(counts["Negative"]), share(counts["Negative"]), delta_color="off")

    left, right = st.columns((1, 1.2))
    with left:
        st.markdown("#### How customers feel")
        st.caption("Sentiment from VADER compound scores (>= 0.05 positive, <= -0.05 negative).")
        draw_sentiment_chart(counts)
    with right:
        st.markdown("#### Top complaint themes")
        st.caption("Keyword themes found in negative or 1-2 star reviews.")
        complaints = top_complaints(df)
        if complaints.empty:
            st.write("No complaint themes found in the current selection.")
        else:
            st.dataframe(complaints, width="stretch", hide_index=True)


def render_ai_summary(df: pd.DataFrame, subject: str) -> None:
    st.markdown("#### AI Review Summary")
    st.caption(
        "Generated by an AI model from the reviews in the current selection only. "
        "Every issue cites the review IDs it is based on - check the evidence below."
    )

    if not ai_service.is_ai_configured():
        st.info(ai_service.NOT_CONFIGURED_MESSAGE)
        return
    if df.empty:
        st.write("No reviews match the current filters.")
        return

    model = ai_service.get_model_name()
    selection_key = hashlib.sha1(
        (subject + model + "|".join(df["review_id"].astype(str))).encode("utf-8")
    ).hexdigest()
    results = st.session_state.setdefault("ai_summaries", {})

    st.write(f"{len(df)} review(s) selected for **{subject}**.")
    if st.button("Generate AI summary", type="primary"):
        with st.spinner("Summarising reviews..."):
            try:
                results[selection_key] = cached_summary(df, subject, model)
            except ai_service.AIServiceError as exc:
                st.error(str(exc))

    result = results.get(selection_key)
    if not result:
        return

    st.markdown(result["summary"])
    note = f"Model: `{result['model']}` · Reviews analysed: {result['reviews_used']}"
    if result["reviews_used"] < result["reviews_total"]:
        note += f" (most recent {result['reviews_used']} of {result['reviews_total']})"
    if result["chunks"] > 1:
        note += f" · Processed in {result['chunks']} batches"
    st.caption(note)

    if result["unknown_ids"]:
        st.warning(
            "The AI cited review ID(s) that do not exist in this selection: "
            + ", ".join(result["unknown_ids"])
            + ". Treat the related statements with caution."
        )
    with st.expander(f"Evidence: {len(result['cited_ids'])} review(s) cited by the AI"):
        cited = df[df["review_id"].astype(str).isin(result["cited_ids"])]
        if cited.empty:
            st.write("The summary did not cite any reviews.")
        else:
            st.dataframe(review_table(cited), width="stretch", hide_index=True)


def render_reviews(df: pd.DataFrame) -> None:
    st.markdown("#### All reviews")
    col_search, col_sentiment = st.columns((3, 1))
    query = col_search.text_input("Search review text, product or ID", placeholder="e.g. battery, delivery, R012")
    sentiment = col_sentiment.selectbox("Sentiment", ["All", "Positive", "Neutral", "Negative"])
    table = review_table(search_reviews(df, query, sentiment))
    st.caption(f"{len(table)} review(s) shown")
    st.dataframe(table, width="stretch", hide_index=True)


def main() -> None:
    st.set_page_config(page_title="ProductPulse AI", page_icon="📊", layout="wide")

    st.sidebar.title("ProductPulse AI")
    st.sidebar.caption("AI-powered product review analysis")
    uploaded = st.sidebar.file_uploader(
        "Upload reviews CSV",
        type="csv",
        help="Columns: review_id, product_name, rating, review_text, review_date (or date).",
    )
    loaded = load_and_score(uploaded.getvalue() if uploaded else None, uploaded.name if uploaded else None)
    df = loaded["dataframe"]

    products = [ALL_PRODUCTS] + sorted(df["product_name"].unique().tolist())
    product = st.sidebar.selectbox("Product", products)
    min_date, max_date = df["review_date"].min().date(), df["review_date"].max().date()
    date_range = st.sidebar.date_input("Review dates", (min_date, max_date), min_value=min_date, max_value=max_date)

    st.sidebar.divider()
    if ai_service.is_ai_configured():
        st.sidebar.success(f"AI enabled · model `{ai_service.get_model_name()}`")
    else:
        st.sidebar.info("AI features off - set AI_API_KEY to enable. Sentiment and themes still work.")

    st.title("ProductPulse AI")
    st.write(
        "Turn customer product reviews into business insights: how customers feel, "
        "what they complain about, and an AI summary backed by real review evidence."
    )
    if loaded["is_sample"]:
        st.warning(f"**Demo mode:** {loaded['source_label']}. Upload a CSV in the sidebar to analyse your own reviews.")
    else:
        st.caption(loaded["source_label"])
    if loaded["error"]:
        st.error(loaded["error"])
    for message in loaded["warnings"]:
        st.info(message)

    view = filter_reviews(df, product, date_range)
    subject = product if product != ALL_PRODUCTS else "all products"

    tab_overview, tab_ai, tab_reviews = st.tabs(["📊 Overview", "🤖 AI Summary", "📋 Reviews"])
    with tab_overview:
        if view.empty:
            st.write("No reviews match the current filters.")
        else:
            render_overview(view)
    with tab_ai:
        render_ai_summary(view, subject)
    with tab_reviews:
        render_reviews(view)


if __name__ == "__main__":
    main()
