"""Dashboard pages. Each page function receives a Context with the filtered data and analysis."""

from __future__ import annotations

import hashlib
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field

import pandas as pd
import streamlit as st

import ai_service
import charts
import compare as comparison
import replies
import report
import styles
import video_reviews
import wishlist
from emotions import EMOTION_ORDER, emotion_counts, emotion_label
from fake_risk import DISCLAIMER as RISK_DISCLAIMER
from insights import (WEIGHTS, build_stats_context, evidence_for_theme, fix_impact, headline, health_score,
                      key_insights, top_words)
from retrieval import find_relevant_reviews
from sentiment import sentiment_counts
from themes import theme_summary
from trends import auto_frequency, review_trends, theme_trends


@dataclass
class Context:
    """Everything a page needs, already filtered to the sidebar selection."""
    reviews: pd.DataFrame          # filtered reviews with sentiment, language and risk columns
    mentions: pd.DataFrame         # theme mentions for those reviews
    priority: pd.DataFrame         # issue priority ranking
    spikes: dict                   # spike detection result
    subject: str                   # e.g. "Nimbus ANC Headphones" or "all products"
    source_label: str
    is_sample: bool
    date_label: str
    insights: list = field(default_factory=list)
    all_reviews: pd.DataFrame | None = None   # every product in the date range (for comparisons)
    all_mentions: pd.DataFrame | None = None

    @property
    def selection_key(self) -> str:
        """Identifies the current selection so AI results are kept per selection."""
        ids = "|".join(self.reviews["review_id"].astype(str))
        return hashlib.sha1(f"{self.subject}|{ai_service.provider_label()}|{ids}".encode()).hexdigest()

    def stats(self) -> str:
        monthly = theme_trends(self.mentions, "Monthly")
        if not monthly.empty:
            monthly = monthly.copy()
            monthly.index = monthly.index.strftime("%Y-%m")
        return build_stats_context(self.reviews, self.mentions, self.priority, self.spikes.get("alerts"), monthly)


PAGES: dict = {}  # filled in by app.py so pages can link to each other


# ---------------------------------------------------------------- shared helpers

def link(page: str, label: str, icon: str) -> None:
    """Link to another dashboard page (if navigation has been set up)."""
    if page in PAGES:
        st.page_link(PAGES[page], label=label, icon=icon)


def review_table(df: pd.DataFrame, extra: list[str] | None = None, order: list[str] | None = None) -> None:
    """Consistent, readable review table."""
    columns = order or ["review_id", "review_date", "product_name", "rating", "sentiment", "language",
                        "review_text"] + (extra or [])
    table = df[[c for c in columns if c in df.columns]].copy()
    st.dataframe(
        table, hide_index=True, width="stretch",
        column_config={
            "review_id": st.column_config.TextColumn("ID", width="small"),
            "review_date": st.column_config.DateColumn("Date", format="DD MMM YYYY", width="medium"),
            "product_name": st.column_config.TextColumn("Product"),
            "rating": st.column_config.NumberColumn("Rating", format="%d ★", width="small"),
            "sentiment": st.column_config.TextColumn("Sentiment", width="small"),
            "sentiment_score": st.column_config.NumberColumn("Score", format="%.2f", width="small"),
            "language": st.column_config.TextColumn("Language", width="small"),
            "review_text": st.column_config.TextColumn("Review", width="large"),
            "risk_level": st.column_config.TextColumn("Risk", width="small"),
            "risk_score": st.column_config.ProgressColumn("Risk score", min_value=0, max_value=100, format="%d"),
            "risk_reasons": st.column_config.ListColumn("Why flagged", width="large"),
            "themes": st.column_config.ListColumn("Themes"),
            "source": st.column_config.TextColumn("Source", width="small"),
            "source_file": st.column_config.TextColumn("File", width="small"),
            "emotion": st.column_config.TextColumn("Emotion", width="small"),
            "relevance": st.column_config.ProgressColumn("Relevance", min_value=0, max_value=1.5, format="%.2f"),
        },
    )


def show_ai_result(result: dict, reviews: pd.DataFrame) -> None:
    """Render an AI answer with its model note, citation check and the cited reviews as evidence."""
    st.markdown(result["text"])
    note = f"AI-generated by {result['model']} from {result['reviews_used']} reviews"
    if result["reviews_used"] < result["reviews_total"]:
        note += f" (most recent {result['reviews_used']} of {result['reviews_total']})"
    if result["chunks"] > 1:
        note += f", processed in {result['chunks']} batches"
    st.caption(note + ". Verify important points against the evidence below.")
    if result["unknown_ids"]:
        st.warning("The AI cited review ID(s) that are not in this selection: " + ", ".join(result["unknown_ids"])
                   + ". Treat the related statements with caution.")
    cited = reviews[reviews["review_id"].astype(str).isin(result["cited_ids"])]
    with st.expander(f"Evidence · {len(cited)} cited review(s), checked against the data"):
        if cited.empty:
            st.write("No reviews were cited.")
        else:
            review_table(cited)


def ai_unavailable_note() -> None:
    st.info(ai_service.NOT_CONFIGURED_MESSAGE + " The sections below are computed directly from the data.", icon="🔑")


def added_videos() -> dict[str, dict]:
    """Video reviews added in this session, by review ID."""
    return {video["review_id"]: video for video in st.session_state.get("video_reviews", [])}


def moment_for(review_id: str, clause: str, videos: dict[str, dict] | None = None) -> tuple[str, str] | None:
    """Link to the moment in a YouTube review where `clause` is said, if it is a video review with captions."""
    video = (videos if videos is not None else added_videos()).get(str(review_id))
    return video_reviews.moment_link(video, clause) if video else None


def theme_quotes(ctx: Context, theme: str, polarity: str, limit: int = 2) -> None:
    videos = added_videos()
    for _, row in evidence_for_theme(ctx.mentions, theme, polarity, limit).iterrows():
        source = ctx.reviews.loc[ctx.reviews["review_id"] == row["review_id"], "source"]
        row["source"] = source.iloc[0] if len(source) else "Text review"
        styles.quote(row, highlight=row["clause"], moment=moment_for(row["review_id"], row["clause"], videos))


# ---------------------------------------------------------------- Welcome tour

WELCOME_TILES = [
    ("🏠", "Overview", "A one-line headline, health score, theme map and the problems to fix first."),
    ("⚖️", "Compare Products", "Two products head to head, with an AI verdict."),
    ("🎬", "Video Reviews", "Add YouTube links or video files and jump to the moment a reviewer says something."),
    ("💡", "Feature Wishlist", "What customers ask you to build next, most requested first."),
    ("✉️", "Reply Studio", "Draft polite, specific replies to unhappy customers in one click."),
    ("📄", "PDF Report", "Download a shareable report from the Overview page."),
]


@st.dialog("👋 Welcome to ProductPulse AI", width="large")
def welcome() -> None:
    st.markdown("Turn hundreds of customer reviews (written **and** video) into decisions. "
                "Everything is computed from your reviews, and every AI claim links back to real ones.")
    styles.tiles(WELCOME_TILES)
    st.caption("You're looking at synthetic demo data. Upload your own CSV from the sidebar at any time. "
               "Reopen this tour with “👋 Welcome tour” in the sidebar.")
    if st.button("Start exploring", type="primary", width="stretch"):
        st.rerun()


# ---------------------------------------------------------------- Overview

def overview(ctx: Context) -> None:
    df = ctx.reviews
    styles.page_header("Dashboard overview", ctx.subject if ctx.subject != "all products" else "All products",
                       "How customers feel, what they complain about, and what to fix first.")
    if df.empty:
        st.warning("No reviews match the current filters.")
        return
    hero_banner(ctx)

    counts = sentiment_counts(df)
    total = len(df)
    # Small trend lines inside the KPI cards (weekly or monthly, depending on the date span).
    trend = review_trends(df, "Monthly" if auto_frequency(df) == "Monthly" else "Weekly")
    trend = trend[trend["reviews"] > 0]
    spark = dict(chart_type="line") if len(trend) >= 3 else {}
    positive_pct = (trend["positive"] / trend["reviews"] * 100).round(1).tolist()

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Reviews analysed", f"{total:,}", border=True,
              **(dict(spark, chart_data=trend["reviews"].tolist(), chart_type="bar") if spark else {}))
    c2.metric("Average rating", f"{df['rating'].mean():.2f} ★", border=True,
              **(dict(spark, chart_data=trend["avg_rating"].tolist()) if spark else {}))
    c3.metric("Positive", f"{counts['Positive'] / total:.0%}", f"{counts['Positive']} reviews",
              delta_color="off", delta_arrow="off", border=True,
              **(dict(spark, chart_data=positive_pct) if spark else {}))
    c4.metric("Negative", f"{counts['Negative'] / total:.0%}", f"{counts['Negative']} reviews",
              delta_color="off", delta_arrow="off", border=True,
              **(dict(spark, chart_data=trend["negative_pct"].tolist()) if spark else {}))
    c5.metric("Health score", f"{health_score(df)}/100", border=True,
              help="50% average rating (scaled 1-5 → 0-1) + 50% net sentiment ((positive − negative) share, scaled to 0-1).")
    if spark:
        st.caption("Mini charts show each metric over time for the selected dates.")

    alerts = ctx.spikes.get("alerts", [])
    if alerts:
        st.space("small")
        cols = st.columns(min(len(alerts), 3))
        for col, alert in zip(cols, alerts[:3]):
            with col:
                styles.alert_card(alert)
        link("trends", label=f"See all {len(alerts)} alert(s) and trends", icon="📈")

    st.space("small")
    left, right = st.columns((1, 1.15), gap="large")
    with left:
        with st.container(border=True):
            styles.section("How customers feel", "VADER sentiment of every review (Hinglish/Hindi supported).")
            st.plotly_chart(charts.sentiment_bars(counts), config={"displayModeBar": False})
            styles.section("Star ratings")
            st.plotly_chart(charts.rating_distribution(df), config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            styles.section("Most important problems", "Ranked by the transparent priority score.")
            if ctx.priority.empty:
                st.write("No complaints detected in this selection.")
            else:
                rows = "".join(
                    styles.issue_row(r.theme, r.level, f"{r.complaint_reviews} complaint reviews · {r.share_pct}% of all · avg {r.avg_rating}★",
                                     charts.LEVEL_COLORS[r.level])
                    for r in ctx.priority.head(5).itertuples()
                )
                styles.html_block(rows)
                top = ctx.priority.iloc[0]
                st.markdown(f"**Example: {top.theme}**")
                theme_quotes(ctx, top.theme, "complaint", 2)
                link("priority", label="Full priority ranking and evidence", icon="🎯")

    summary = theme_summary(ctx.mentions, total)
    if not summary.empty and (summary["praise"] + summary["complaints"]).sum() > 0:
        with st.container(border=True):
            styles.section("Theme map", "Every theme customers talk about. Bigger and higher = discussed more; "
                                        "left = mostly complaints, right = mostly praise.")
            st.plotly_chart(charts.theme_map(summary), config={"displayModeBar": False})

    left, right = st.columns((1, 1.4), gap="large")
    with left:
        with st.container(border=True):
            styles.section("Emotions", "The main feeling in each review, beyond positive or negative.")
            st.plotly_chart(charts.emotion_bars(emotion_counts(df), {e: emotion_label(e) for e in EMOTION_ORDER}),
                            config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            styles.section("In customers' words", "Words used most when praising (blue) and complaining (red). "
                                                  "Hover a word to see how many reviews use it.")
            praise_col, complaint_col = st.columns(2)
            with praise_col:
                styles.word_cloud(top_words(ctx.mentions, "praise", 22), charts.SENTIMENT_COLORS["Positive"])
            with complaint_col:
                styles.word_cloud(top_words(ctx.mentions, "complaint", 22), charts.SENTIMENT_COLORS["Negative"])

    left, right = st.columns(2, gap="large")
    with left:
        with st.container(border=True):
            styles.section("What customers love", "Themes most often praised.")
            praised = summary[summary["praise"] >= 2].sort_values("praise", ascending=False).head(3)
            if praised.empty:
                st.write("No recurring praise found.")
            for row in praised.itertuples():
                st.markdown(f"**{row.theme}** · {row.praise} reviews ({row.praise_pct}%)")
                theme_quotes(ctx, row.theme, "praise", 1)
    with right:
        with st.container(border=True):
            styles.section("Key insights", "Computed from the data, each backed by review IDs.")
            for item in [i for i in ctx.insights if i["kind"] != "overview"][:4]:
                styles.insight_card(item["text"], item["kind"], item["evidence"])
            link("ai", label="AI summary & recommendations", icon="✨")

    with st.container(border=True):
        styles.section("AI summary", "Generated from the reviews in this selection.")
        overall_ai_block(ctx, compact=True)


def hero_banner(ctx: Context) -> None:
    """Health ring plus a headline: computed from the data, or written by the AI on request."""
    store = st.session_state.setdefault("ai_results", {})
    key = (ctx.selection_key, "headline")
    ai_result = store.get(key)
    text = ai_result["text"] if ai_result else headline(ctx.reviews, ctx.mentions, ctx.priority)
    chips = [ctx.date_label, f"{len(ctx.reviews):,} reviews", ctx.source_label]
    styles.hero(health_score(ctx.reviews), "✨ AI headline" if ai_result else "Headline", text, chips)
    left, right = st.columns((3, 1.2), vertical_alignment="center")
    with left:
        if ai_result:
            st.caption(f"Written by {ai_result['model']}. Based on reviews "
                       + (", ".join(ai_result["cited_ids"]) or "in this selection") + ".")
        elif ai_service.is_ai_configured():
            if st.button("✨ Write the headline with AI", key="ai_headline"):
                with st.spinner("Reading the reviews..."):
                    try:
                        store[key] = ai_service.generate_headline(ctx.reviews, ctx.subject, ctx.stats())
                        st.rerun()
                    except ai_service.AIServiceError as exc:
                        st.error(str(exc))
    summary = store.get((ctx.selection_key, "overall"))
    name = "all-products" if ctx.subject == "all products" else ctx.subject.lower().replace(" ", "-")
    right.download_button(
        "📄 Download PDF report", lambda: report.build_report(ctx, summary["text"] if summary else None),
        f"productpulse-report-{name}.pdf", "application/pdf", width="stretch", on_click="ignore",
        help="A shareable summary of this selection. Includes the AI summary if you have generated it.")


def overall_ai_block(ctx: Context, compact: bool = False) -> None:
    """Overall AI summary with a generate button; shared by Overview and AI Insights."""
    if not ai_service.is_ai_configured():
        st.info(ai_service.NOT_CONFIGURED_MESSAGE, icon="🔑")
        return
    store = st.session_state.setdefault("ai_results", {})
    key = (ctx.selection_key, "overall")
    if key not in store:
        if st.button("Generate AI summary", type="primary", key=f"gen_overall_{compact}"):
            with st.spinner("Reading reviews and writing the summary..."):
                try:
                    store[key] = ai_service.generate_review_summary(ctx.reviews, ctx.subject)
                except ai_service.AIServiceError as exc:
                    st.error(str(exc))
    if key in store:
        show_ai_result(store[key], ctx.reviews)


# ---------------------------------------------------------------- AI Insights

AI_TASKS = {
    "overall": ("Overall Summary", lambda ctx: ai_service.generate_review_summary(ctx.reviews, ctx.subject)),
    "positive": ("Positive Feedback", lambda ctx: ai_service.generate_positive_summary(
        ctx.reviews[ctx.reviews["sentiment"] == "Positive"], ctx.subject)),
    "negative": ("Negative Feedback", lambda ctx: ai_service.generate_negative_summary(
        ctx.reviews[ctx.reviews["sentiment"] == "Negative"], ctx.subject)),
    "insights": ("Insights & Actions", lambda ctx: ai_service.generate_key_insights(ctx.reviews, ctx.subject, ctx.stats())),
}


def run_ai_tasks(ctx: Context, names: list[str]) -> dict[str, str]:
    """Run several AI tasks in parallel threads. Returns {task: error message} for failures."""
    store = st.session_state.setdefault("ai_results", {})
    errors: dict[str, str] = {}
    with ThreadPoolExecutor(max_workers=4) as pool:
        futures = {name: pool.submit(AI_TASKS[name][1], ctx) for name in names}
        for name, future in futures.items():
            try:
                store[(ctx.selection_key, name)] = future.result()
            except ai_service.AIServiceError as exc:
                errors[name] = str(exc)
    return errors


def ai_insights(ctx: Context) -> None:
    styles.page_header("AI analysis", "AI Review Insights",
                       "Summaries, praise, complaints and recommended actions, every point citing real reviews.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews", ai_service.provider_label()])
    if ctx.reviews.empty:
        st.warning("No reviews match the current filters.")
        return
    configured = ai_service.is_ai_configured()
    store = st.session_state.setdefault("ai_results", {})
    missing = [n for n in AI_TASKS if (ctx.selection_key, n) not in store]

    if not configured:
        ai_unavailable_note()
    elif missing:
        if st.button("✨ Generate full AI analysis", type="primary"):
            with st.status("Analysing reviews with AI...", expanded=False) as status:
                errors = run_ai_tasks(ctx, missing)
                if errors:
                    status.update(label="Some AI sections failed", state="error")
                    for name, message in errors.items():
                        st.error(f"{AI_TASKS[name][0]}: {message}")
                else:
                    status.update(label="AI analysis complete", state="complete")
        st.caption("Runs four grounded AI requests in parallel: overall summary, positive feedback, negative feedback, insights & actions.")

    tabs = st.tabs([AI_TASKS[n][0] for n in AI_TASKS])
    for tab, name in zip(tabs, AI_TASKS):
        with tab:
            result = store.get((ctx.selection_key, name))
            if result:
                show_ai_result(result, ctx.reviews)
            elif configured:
                st.caption("Not generated yet. Use the button above.")
            computed_fallback(ctx, name)


def computed_fallback(ctx: Context, name: str) -> None:
    """Data-driven content shown under each AI tab (and instead of it when AI is off)."""
    total = len(ctx.reviews)
    summary = theme_summary(ctx.mentions, total)
    st.divider()
    if name == "overall":
        styles.section("Computed overview")
        for item in ctx.insights[:1]:
            styles.insight_card(item["text"], item["kind"])
    elif name in ("positive", "negative"):
        polarity, column = ("praise", "praise") if name == "positive" else ("complaint", "complaints")
        styles.section("Most mentioned " + ("strengths" if name == "positive" else "problems"),
                       "Computed from theme detection, with real review quotes.")
        top = summary[summary[column] > 0].sort_values(column, ascending=False).head(4)
        if top.empty:
            st.write("Nothing found in this selection.")
        for row in top.itertuples():
            st.markdown(f"**{row.theme}** · {getattr(row, column)} reviews")
            theme_quotes(ctx, row.theme, polarity, 2)
    else:
        styles.section("Computed insights", "Calculated directly from the data, each with evidence review IDs.")
        for item in ctx.insights:
            styles.insight_card(item["text"], item["kind"], item["evidence"])


# ---------------------------------------------------------------- Ask Your Reviews

SUGGESTED_QUESTIONS = [
    "What are the biggest complaints?",
    "What do customers like most?",
    "Why are customers giving low ratings?",
    "Are delivery complaints increasing?",
    "What should the company improve first?",
]


def ask(ctx: Context) -> None:
    styles.page_header("AI analysis", "Ask Your Reviews",
                       "Ask a question in plain English. Answers use only your reviews and computed statistics.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews"])
    if ctx.reviews.empty:
        st.warning("No reviews match the current filters.")
        return
    if not ai_service.is_ai_configured():
        st.info("AI answers need AI_API_KEY. Without it, you will see the most relevant reviews and statistics "
                "for your question instead.", icon="🔑")

    history = st.session_state.setdefault("qa_history", {}).setdefault(ctx.selection_key, [])
    picked = st.pills("Try a question", SUGGESTED_QUESTIONS, key=f"pill_{ctx.selection_key[:8]}_{len(history)}")
    typed = st.chat_input("Ask about your reviews, e.g. “Is battery life a common problem?”")
    question = typed or picked

    for item in history:
        render_qa(item, ctx)
    if question:
        item = answer(ctx, question)
        history.append(item)
        render_qa(item, ctx)
    if history and st.button("Clear conversation", type="tertiary"):
        history.clear()
        st.rerun()


def answer(ctx: Context, question: str) -> dict:
    relevant = find_relevant_reviews(ctx.reviews, question, ctx.mentions, limit=60)
    item = {"question": question, "relevant_ids": relevant["review_id"].astype(str).tolist(), "result": None, "error": None}
    if ai_service.is_ai_configured():
        with st.spinner("Searching reviews and writing an answer..."):
            try:
                item["result"] = ai_service.answer_question(question, relevant, ctx.stats(), ctx.subject)
            except ai_service.AIServiceError as exc:
                item["error"] = str(exc)
    return item


def render_qa(item: dict, ctx: Context) -> None:
    with st.chat_message("user"):
        st.write(item["question"])
    with st.chat_message("assistant", avatar="✨"):
        if item["result"]:
            show_ai_result(item["result"], ctx.reviews)
            return
        if item["error"]:
            st.error(item["error"])
        relevant = ctx.reviews[ctx.reviews["review_id"].astype(str).isin(item["relevant_ids"][:8])]
        st.markdown("**Most relevant reviews** (found by text search; no AI used):")
        for _, row in relevant.iterrows():
            styles.quote(row)
        with st.expander("Statistics for this selection"):
            st.code(ctx.stats(), language=None)


# ---------------------------------------------------------------- Priority Issues

def priority(ctx: Context) -> None:
    styles.page_header("Issues", "Priority Issues",
                       "Which problems matter most, why, and the real reviews behind each one.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews"])
    if ctx.priority.empty:
        st.success("No complaints detected in this selection.")
        return
    with st.expander("How the priority score works"):
        st.markdown(
            f"""
**Priority score (0-100)** = {WEIGHTS['frequency']} × frequency + {WEIGHTS['negativity']} × negativity
+ {WEIGHTS['low_ratings']} × low ratings + {WEIGHTS['recent_rise']} × recent rise

- **Frequency**: share of all reviews complaining about the issue (20% or more = full marks)
- **Negativity**: how negative the complaint sentences are (average VADER score)
- **Low ratings**: share of those complaint reviews rated 1-2 stars
- **Recent rise**: 1 if the complaint rate rose 50%+ recently, 0.5 if it rose, 0 otherwise

Levels need both a score **and** enough evidence, so one complaint is never Critical:
**Critical** ≥ 70 and ≥ 5 reviews · **High** ≥ 50 and ≥ 3 · **Medium** ≥ 30 and ≥ 2 · otherwise **Low**.
"""
        )

    left, right = st.columns((1, 1), gap="large")
    with left:
        with st.container(border=True):
            styles.section("Priority ranking")
            st.plotly_chart(charts.priority_scores(ctx.priority), config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            styles.section("Praise vs complaints by theme", "Number of reviews praising (right) or complaining (left).")
            st.plotly_chart(charts.praise_vs_complaints(theme_summary(ctx.mentions, len(ctx.reviews))),
                            config={"displayModeBar": False})

    impact = fix_impact(ctx.reviews, ctx.mentions, ctx.priority)
    if not impact.empty and impact["gain"].max() > 0:
        with st.container(border=True):
            best = impact.iloc[0]
            styles.section("💰 If you fixed it",
                           "Estimated average rating if reviews complaining about each issue rated like the rest. "
                           "Optimistic: some of those reviews mention other problems too.")
            st.markdown(f"Fixing **{best.theme}** could lift the average rating from **{best.current_avg:.2f}★** "
                        f"to about **{best.projected_avg:.2f}★** (+{best.gain:.2f}), the biggest gain of any issue.")
            st.plotly_chart(charts.fix_impact(impact), config={"displayModeBar": False})

    table = ctx.priority[["theme", "level", "score", "complaint_reviews", "share_pct", "avg_rating",
                          "recent_rate_pct", "earlier_rate_pct"]]
    st.dataframe(table, hide_index=True, width="stretch", column_config={
        "theme": "Issue", "level": "Priority",
        "score": st.column_config.ProgressColumn("Score", min_value=0, max_value=100, format="%.0f"),
        "complaint_reviews": st.column_config.NumberColumn("Complaint reviews"),
        "share_pct": st.column_config.NumberColumn("% of all reviews", format="%.1f%%"),
        "avg_rating": st.column_config.NumberColumn("Avg rating", format="%.2f ★"),
        "recent_rate_pct": st.column_config.NumberColumn("Recent rate", format="%.1f%%"),
        "earlier_rate_pct": st.column_config.NumberColumn("Earlier rate", format="%.1f%%"),
    })

    styles.section("Evidence by issue", "Real reviews supporting each issue. The highlighted text is what was detected.")
    for row in ctx.priority.itertuples():
        title = f"{row.theme} · {row.level} priority · {row.complaint_reviews} review(s)"
        with st.expander(title, expanded=row.level in ("Critical", "High") and row.Index < 2):
            st.caption(f"Score {row.score} = frequency {row.frequency} · negativity {row.negativity} · "
                       f"low ratings {row.low_ratings} · recent rise {row.recent_rise}")
            if row.complaint_reviews == 1:
                st.caption("Isolated: only one review mentions this, so it is not yet a recurring pattern.")
            theme_quotes(ctx, row.theme, "complaint", 3)
            all_rows = ctx.reviews[ctx.reviews["review_id"].isin(
                ctx.mentions.loc[(ctx.mentions["theme"] == row.theme) & (ctx.mentions["polarity"] == "complaint"), "review_id"])]
            if len(all_rows) > 3 and st.toggle(f"Show all {len(all_rows)} reviews", key=f"all_{row.theme}"):
                review_table(all_rows.sort_values("review_date", ascending=False))


# ---------------------------------------------------------------- Trends & Alerts

def trends(ctx: Context) -> None:
    styles.page_header("Issues", "Trends & Alerts", "How feedback changes over time, and unusual recent spikes.",
                       [ctx.subject, ctx.date_label])
    df = ctx.reviews
    if df.empty:
        st.warning("No reviews match the current filters.")
        return

    styles.section("Spike alerts", "Detected patterns, not confirmed causes. Recent window vs the weeks before it.")
    spikes = ctx.spikes
    if spikes["status"] != "ok":
        st.info(spikes["message"], icon="ℹ️")
    elif not spikes["alerts"]:
        st.success("No unusual spikes detected. " + spikes["message"], icon="✅")
    else:
        st.caption(spikes["message"])
        cols = st.columns(2)
        for i, alert in enumerate(spikes["alerts"]):
            with cols[i % 2]:
                styles.alert_card(alert)

    auto = auto_frequency(df)
    choice = st.segmented_control("Group by", ["Auto", "Daily", "Weekly", "Monthly"], default="Auto",
                                  key="trend_frequency")
    frequency = auto if choice in (None, "Auto") else choice
    trend = review_trends(df, frequency)
    st.caption(f"Grouped {frequency.lower()}.")

    left, right = st.columns(2, gap="large")
    with left:
        with st.container(border=True):
            styles.section("Review volume by sentiment")
            st.plotly_chart(charts.sentiment_volume(trend), config={"displayModeBar": False})
        with st.container(border=True):
            styles.section("Negative reviews (% of period)")
            st.plotly_chart(charts.line_chart(trend, "negative_pct", "Negative %", charts.SENTIMENT_COLORS["Negative"],
                                              [0, 100], "%"), config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            video_rows = df[df["source"] != ai_service.TEXT_SOURCE]
            styles.section("Average rating", "🎬 Stars mark video reviews." if len(video_rows) else "")
            events = pd.DataFrame({"date": video_rows["review_date"], "value": video_rows["rating"],
                                   "label": video_rows["review_id"].map(
                                       lambda i: added_videos().get(i, {}).get("video_title", i))})
            st.plotly_chart(charts.line_chart(trend, "avg_rating", "Average rating", "#2a78d6", [0.6, 5.6],
                                              events=events),
                            config={"displayModeBar": False})
        with st.container(border=True):
            # One level coarser than the other charts: five theme lines per week are too noisy to read.
            theme_frequency = {"Daily": "Weekly", "Weekly": "Monthly", "Monthly": "Monthly"}[frequency]
            styles.section("Complaint themes over time",
                           f"Top 5 themes by complaint volume, grouped {theme_frequency.lower()} for readability.")
            themes_over_time = theme_trends(ctx.mentions, theme_frequency)
            if themes_over_time.empty:
                st.write("No complaints in this selection.")
            else:
                st.plotly_chart(charts.theme_trend_lines(themes_over_time), config={"displayModeBar": False})

    with st.expander("Trend data table"):
        st.dataframe(trend, hide_index=True, width="stretch")


# ---------------------------------------------------------------- Review Integrity

def integrity(ctx: Context) -> None:
    styles.page_header("Trust", "Review Integrity", "Potentially suspicious reviews, with the reasons they were flagged.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews"])
    df = ctx.reviews
    st.warning(f"**{RISK_DISCLAIMER}** Signals such as duplicate text or review bursts can have innocent explanations. "
               "Use this list to decide what to look at more closely, never to accuse customers.", icon="⚠️")
    if df.empty:
        return

    levels = df["risk_level"].value_counts()
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("High risk", int(levels.get("High", 0)), border=True)
    c2.metric("Medium risk", int(levels.get("Medium", 0)), border=True)
    c3.metric("Low risk", int(levels.get("Low", 0)), border=True)
    c4.metric("Near-duplicates", int((df["max_similarity"] >= 0.9).sum()), border=True,
              help="Reviews of similar length with at least 90% text similarity to another review.")

    left, right = st.columns((1, 1.4), gap="large")
    with left:
        with st.container(border=True):
            styles.section("Risk levels")
            st.plotly_chart(charts.risk_levels(df), config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            styles.section("How the risk score works", "Points add up per review (capped at 100).")
            st.markdown("""
| Signal | Points |
|---|---|
| Near-duplicate text (≥ 90% similar) | +40 |
| Very similar text (≥ 75% similar) | +20 |
| Burst of same-rating reviews on one day | +20 |
| Generic text, no product detail | +15 |
| Star rating contradicts text | +15 |
| Promotional phrasing | +10 |
| Excessive "!!!" or capitals | +10 |
| Extreme rating with another signal | +5 |

**High** ≥ 55 · **Medium** ≥ 30 · **Low** < 30
""")

    styles.section("Flagged reviews", "Each row lists every signal that contributed to its score.")
    level_filter = st.pills("Show", ["High", "Medium", "Low"], default=["High", "Medium"], selection_mode="multi",
                            key="risk_filter")
    flagged = df[df["risk_level"].isin(level_filter or [])].sort_values("risk_score", ascending=False)
    st.caption(f"{len(flagged)} review(s)")
    columns = ["review_id", "risk_level", "risk_score", "risk_reasons", "review_text", "rating",
               "review_date", "product_name"]
    review_table(flagged[columns], extra=["risk_level", "risk_score", "risk_reasons"], order=columns)


# ---------------------------------------------------------------- Review Explorer

def explorer(ctx: Context) -> None:
    styles.page_header("Data", "Review Explorer", "Search and filter every review with its analysis.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews"])
    df = ctx.reviews.copy()
    if df.empty:
        st.warning("No reviews match the current filters.")
        return
    theme_lists = ctx.mentions.assign(label=ctx.mentions["theme"] + " (" + ctx.mentions["polarity"] + ")") \
        .groupby("review_id")["label"].apply(list)
    df["themes"] = df["review_id"].map(theme_lists).apply(lambda v: v if isinstance(v, list) else [])

    c1, c2, c3, c4 = st.columns((2.2, 1, 1, 1))
    query = c1.text_input("Search", placeholder="Words, product or review ID, e.g. battery, delivery, D012")
    sentiments = c2.multiselect("Sentiment", ["Positive", "Neutral", "Negative"])
    languages = c3.multiselect("Language", ["English", "Hinglish", "Hindi"])
    risks = c4.multiselect("Risk", ["High", "Medium", "Low"])
    c5, c6, c7 = st.columns((1, 1.6, 1))
    ratings = c5.slider("Rating", 1, 5, (1, 5))
    theme_filter = c6.multiselect("Theme", sorted(ctx.mentions["theme"].unique()))
    sources = c7.multiselect("Source", sorted(df["source"].unique()))
    emotion_filter = st.pills("Emotion", [e for e in EMOTION_ORDER if e in set(df["emotion"])],
                              selection_mode="multi", format_func=emotion_label, key="explorer_emotions")

    view = df[(df["rating"] >= ratings[0]) & (df["rating"] <= ratings[1])]
    if query.strip():
        q = query.strip()
        view = view[view["review_text"].str.contains(q, case=False, regex=False)
                    | view["product_name"].str.contains(q, case=False, regex=False)
                    | view["review_id"].astype(str).str.contains(q, case=False, regex=False)]
    if sentiments:
        view = view[view["sentiment"].isin(sentiments)]
    if languages:
        view = view[view["language"].isin(languages)]
    if risks:
        view = view[view["risk_level"].isin(risks)]
    if theme_filter:
        ids = ctx.mentions.loc[ctx.mentions["theme"].isin(theme_filter), "review_id"]
        view = view[view["review_id"].isin(ids)]
    if sources:
        view = view[view["source"].isin(sources)]
    if emotion_filter:
        view = view[view["emotion"].isin(emotion_filter)]
    if "source_file" in df.columns and df["source_file"].nunique() > 1:
        files = st.multiselect("File", sorted(df["source_file"].dropna().unique()), key="explorer_files",
                               placeholder="All uploaded files")
        if files:
            view = view[view["source_file"].isin(files)]

    top_left, top_mid, top_right = st.columns((2.2, 1.2, 1), vertical_alignment="center")
    top_left.caption(f"{len(view)} of {len(df)} reviews")
    layout = top_mid.segmented_control("View", ["🗂️ Cards", "📋 Table"], default="🗂️ Cards",
                                       key="explorer_view", label_visibility="collapsed")
    export = view.drop(columns=["risk_reasons", "themes"]).assign(
        themes=view["themes"].str.join("; "), risk_reasons=view["risk_reasons"].str.join("; "))
    top_right.download_button("Download CSV", export.to_csv(index=False).encode("utf-8"),
                              "productpulse_reviews.csv", "text/csv", width="stretch")
    view = view.sort_values("review_date", ascending=False)
    if layout == "📋 Table":
        review_table(view, extra=["sentiment_score", "emotion", "themes", "risk_level", "source", "source_file"])
    else:
        review_cards(ctx, view)

    with st.container(border=True):
        styles.section("Languages", "Detected with a script + vocabulary heuristic.")
        st.plotly_chart(charts.language_mix(df), config={"displayModeBar": False})


# ---------------------------------------------------------------- Video Reviews

ESTIMATE_RATING = "Estimate from what the reviewer says"


def video_fields(form: str, products: list[str], product_help: str, date_help: str) -> tuple:
    """Product, rating and date inputs shared by both ways of adding videos."""
    c1, c2, c3 = st.columns((2, 1.4, 1))
    product = c1.selectbox("Product", products, index=None, accept_new_options=True, key=f"{form}_product",
                           placeholder="Choose a product or type a new name", help=product_help)
    rating = c2.selectbox("Star rating", [ESTIMATE_RATING, 5, 4, 3, 2, 1], key=f"{form}_rating",
                          help="Videos have no star rating. By default it is estimated from the sentiment of "
                               "what the reviewer says, and shown as estimated.")
    date = c3.date_input("Review date", value=None, key=f"{form}_date", help=date_help)
    return product or "", None if rating == ESTIMATE_RATING else int(rating), date


def add_videos(items: list, existing_id, make) -> None:
    """Transcribe each item, add the new reviews to the session, then rerun so every page includes them."""
    added = st.session_state.setdefault("video_reviews", [])
    known = {video["review_id"] for video in added}
    messages = []
    with st.status(f"Processing {len(items)} video(s). Longer videos can take a minute or two...",
                   expanded=True) as status:
        for item in items:
            name = getattr(item, "name", item)
            if existing_id(item) in known:
                messages.append(("warning", f"{name} was already added."))
                continue
            st.markdown(f"**{name}**")
            try:
                review = make(item, lambda message: st.write(f"↳ {message}..."))
            except video_reviews.VideoReviewError as exc:
                messages.append(("error", str(exc)))
                continue
            added.append(review)
            known.add(review["review_id"])
            messages.append(("success", f"Added “{review['video_title']}” as review {review['review_id']} "
                                        f"({review['transcript_method']}, {len(review['review_text'].split())} words)."))
        status.update(label="Done", state="complete", expanded=False)
    if not video_reviews.save(added):
        messages.append(("warning", "The videos could not be saved to disk, so they will only last for this session."))
    st.session_state["video_messages"] = messages
    st.rerun()


def videos(ctx: Context) -> None:
    added = st.session_state.setdefault("video_reviews", [])
    styles.page_header("Data", "Video Reviews",
                       "Add review videos from YouTube or your computer. Each video is transcribed and then "
                       "analysed like a written review on every page.", [f"{len(added)} video(s) added"])
    for kind, message in st.session_state.pop("video_messages", []):
        getattr(st, kind)(message)

    products = sorted(ctx.reviews["product_name"].unique()) if not ctx.reviews.empty else []
    can_transcribe = ai_service.can_transcribe_video()
    youtube_tab, upload_tab = st.tabs(["▶️ YouTube links", "📁 Upload video files"])

    with youtube_tab:
        st.caption("The video's captions are used when it has them (no API key needed). Videos without captions "
                   + ("are transcribed by Gemini." if can_transcribe else "need a Gemini API key."))
        with st.form("youtube_form", border=False, clear_on_submit=True):
            links = st.text_area("YouTube links", height=110,
                                 placeholder="One link per line, e.g.\nhttps://www.youtube.com/watch?v=...\nhttps://youtu.be/...")
            product, rating, date = video_fields("yt", products, "Leave empty to use the video's title.",
                                                 "Leave empty to use the date the video was uploaded.")
            submitted = st.form_submit_button("Add YouTube videos", type="primary")
        if submitted:
            lines = list(dict.fromkeys(line.strip() for line in links.splitlines() if line.strip()))
            if not lines:
                st.warning("Paste at least one YouTube link.")
            else:
                add_videos(
                    lines,
                    lambda line: video_reviews.review_id(video_reviews.YOUTUBE_SOURCE, video_reviews.youtube_key(
                        video_reviews.parse_youtube_id(line) or line)),
                    lambda line, step: video_reviews.youtube_review(line, product, rating, date, step))

    with upload_tab:
        if not can_transcribe:
            st.info(ai_service.VIDEO_NEEDS_GEMINI_MESSAGE, icon="🔑")
        else:
            st.caption("Gemini transcribes the speech in each file. Audio files (MP3, WAV, M4A) work too.")
        with st.form("upload_form", border=False, clear_on_submit=True):
            files = st.file_uploader("Video files", type=list(video_reviews.VIDEO_MIME_TYPES),
                                     accept_multiple_files=True, disabled=not can_transcribe)
            product, rating, date = video_fields("up", products, "Which product the videos review (required).",
                                                 "Leave empty to use today's date.")
            submitted = st.form_submit_button("Transcribe and add", type="primary", disabled=not can_transcribe)
        if submitted:
            if not files:
                st.warning("Choose at least one video file.")
            elif not product.strip():
                st.warning("Choose or type the product these videos review.")
            else:
                add_videos(
                    files,
                    lambda f: video_reviews.review_id(video_reviews.UPLOAD_SOURCE,
                                                      video_reviews.upload_key(f.getvalue())),
                    lambda f, step: video_reviews.uploaded_video_review(f.getvalue(), f.name, product, rating, date,
                                                                        step))

    if not added:
        return
    st.divider()
    styles.section("Added videos", "Saved on this computer, so they are still here next time you open the app.")
    video_summary(ctx, added)
    analysed = ctx.reviews.set_index("review_id")
    hidden = [v for v in added if v["review_id"] not in analysed.index]
    if hidden:
        st.caption(f"{len(hidden)} video(s) are outside the current product or date filter, so they are not in "
                   "the analysis right now.")
    columns = st.columns(3, gap="medium")
    for i, video in enumerate(added):
        sentiment = analysed.loc[video["review_id"], "sentiment"] if video["review_id"] in analysed.index else None
        thumbnail = video_reviews.thumbnail_url(video["video_id"]) if video.get("video_id") else None
        with columns[i % 3]:
            styles.html_block(styles.video_card(video, sentiment, thumbnail,
                                                video_reviews.format_views(video.get("views"))))
            with st.popover("Transcript & key moments", width="stretch"):
                video_details(ctx, video)
    st.space("small")
    if st.button("Remove all videos", icon="🗑️"):
        st.session_state["video_reviews"] = []
        video_reviews.save([])
        st.rerun()


def video_summary(ctx: Context, added: list[dict]) -> None:
    """Audience reach: how many people watched the videos, and how many watched a negative one."""
    sentiments = ctx.reviews.set_index("review_id")["sentiment"]
    views = [int(v.get("views") or 0) for v in added]
    negative = sum(n for v, n in zip(added, views) if sentiments.get(v["review_id"]) == "Negative")
    c1, c2, c3 = st.columns(3)
    c1.metric("Video reviews", len(added), border=True)
    c2.metric("Total views", video_reviews.format_views(sum(views)).replace(" views", "") or "–", border=True,
              help="YouTube view counts when the videos were added. Uploaded files have no views.")
    c3.metric("Views of negative videos", video_reviews.format_views(negative).replace(" views", "") or "0",
              border=True, help="How many people may have seen a negative video review: its reach.")


def video_details(ctx: Context, video: dict) -> None:
    """Key moments (what the reviewer praises or criticises, linked to the second they say it) and the transcript."""
    st.markdown(f"**{video['video_title']}**")
    st.caption(f"{video['transcript_method']} · {len(video['review_text'].split()):,} words · "
               f"rating {video['rating']}★{' (estimated)' if video['rating_estimated'] else ''}")
    moments = ctx.mentions[(ctx.mentions["review_id"] == video["review_id"])
                           & ctx.mentions["polarity"].isin(["praise", "complaint"])]
    if not moments.empty:
        styles.section("Key moments")
        for row in moments.itertuples():
            icon = "👍" if row.polarity == "praise" else "👎"
            link_info = video_reviews.moment_link(video, row.clause)
            when = f"[▶ {link_info[1]}]({link_info[0]}) · " if link_info else ""
            clause = row.clause if len(row.clause) <= 220 else row.clause[:220].rsplit(" ", 1)[0] + " …"
            st.markdown(f"{when}{icon} **{row.theme}**: “{clause}”")
        if not video.get("timestamps"):
            st.caption("Time links need YouTube captions, so they are not available for this video.")
    styles.section("Transcript")
    st.text(video["review_text"])
    if st.button("Remove this video", key=f"remove_{video['review_id']}", icon="🗑️"):
        st.session_state["video_reviews"] = [v for v in st.session_state.get("video_reviews", [])
                                             if v["review_id"] != video["review_id"]]
        video_reviews.save(st.session_state["video_reviews"])
        st.rerun()


# ---------------------------------------------------------------- Compare Products

def compare(ctx: Context) -> None:
    styles.page_header("Dashboard", "Compare Products",
                       "Two products head to head: ratings, sentiment and how customers feel about each theme.",
                       [ctx.date_label])
    reviews = ctx.all_reviews if ctx.all_reviews is not None else ctx.reviews
    mentions = ctx.all_mentions if ctx.all_mentions is not None else ctx.mentions
    products = reviews["product_name"].value_counts().index.tolist()
    if len(products) < 2:
        st.info("Comparing needs at least two products in the selected dates. Choose a dataset with more "
                "products, or widen the date range.", icon="⚖️")
        return
    c1, c2 = st.columns(2)
    name_a = c1.selectbox("Product A", products, index=0, key="compare_a")
    name_b = c2.selectbox("Product B", [p for p in products if p != name_a], index=0, key="compare_b")
    reviews_a, reviews_b = reviews[reviews["product_name"] == name_a], reviews[reviews["product_name"] == name_b]
    mentions_a = mentions[mentions["review_id"].isin(reviews_a["review_id"])]
    mentions_b = mentions[mentions["review_id"].isin(reviews_b["review_id"])]
    metrics_a, metrics_b = comparison.product_metrics(reviews_a), comparison.product_metrics(reviews_b)

    formats = {"Reviews": "{:,}", "Average rating": "{:.2f} ★", "Positive": "{:.0f}%", "Negative": "{:.0f}%",
               "Health score": "{}/100"}
    rows = [(metric, formats[metric].format(metrics_a[column]), formats[metric].format(metrics_b[column]),
             comparison.winner(metric, metrics_a, metrics_b))
            for metric, (column, _) in comparison.METRICS.items()]
    styles.versus((name_a, name_b), rows, tuple(charts.COMPARE_COLORS))
    if min(metrics_a["reviews"], metrics_b["reviews"]) < 10:
        st.caption("⚠️ One product has fewer than 10 reviews in this range, so treat the differences with caution.")

    table = comparison.theme_table(mentions_a, mentions_b)
    left, right = st.columns((1.1, 1), gap="large")
    with left:
        with st.container(border=True):
            styles.section("Theme satisfaction", "Share of reviews mentioning a theme that praise it (0-100). "
                                                 f"Needs {comparison.MIN_THEME_MENTIONS}+ reviews per theme.")
            if table.dropna(subset=["satisfaction_a", "satisfaction_b"], how="all").empty:
                st.write("Not enough theme mentions to compare yet.")
            else:
                st.plotly_chart(charts.theme_radar(table, name_a, name_b), config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            styles.section("Star ratings", "Share of each product's reviews.")
            st.plotly_chart(charts.compare_ratings(reviews_a, name_a, reviews_b, name_b),
                            config={"displayModeBar": False})
        with st.container(border=True):
            styles.section("Clear differences", "Themes where satisfaction differs by 15 points or more.")
            for name, side, color in ((name_a, "a", charts.COMPARE_COLORS[0]), (name_b, "b", charts.COMPARE_COLORS[1])):
                better, _ = comparison.strengths_and_weaknesses(table, side)
                text = ", ".join(f"**{t}**" for t in better) if better else "nothing clearly better"
                styles.html_block(f'<div style="margin:0.25rem 0"><span style="color:{color};font-weight:700">'
                                  f'{styles.md_to_html(name)}</span> wins on {styles.md_to_html(text)}</div>')

    with st.expander("Theme-by-theme numbers"):
        st.dataframe(table, hide_index=True, width="stretch", column_config={
            "theme": "Theme",
            "praise_a": st.column_config.NumberColumn(f"{name_a} · praise"),
            "complaints_a": st.column_config.NumberColumn(f"{name_a} · complaints"),
            "satisfaction_a": st.column_config.ProgressColumn(f"{name_a} · satisfaction", min_value=0, max_value=100, format="%.0f"),
            "praise_b": st.column_config.NumberColumn(f"{name_b} · praise"),
            "complaints_b": st.column_config.NumberColumn(f"{name_b} · complaints"),
            "satisfaction_b": st.column_config.ProgressColumn(f"{name_b} · satisfaction", min_value=0, max_value=100, format="%.0f"),
        })

    with st.container(border=True):
        styles.section("✨ AI verdict", "Which product customers prefer and why, with cited reviews.")
        if not ai_service.is_ai_configured():
            st.info(ai_service.NOT_CONFIGURED_MESSAGE, icon="🔑")
            return
        store = st.session_state.setdefault("ai_results", {})
        ids = "|".join(sorted(reviews_a["review_id"].astype(str)) + sorted(reviews_b["review_id"].astype(str)))
        key = ("compare", name_a, name_b, hashlib.sha1(ids.encode()).hexdigest(), ai_service.provider_label())
        if key not in store and st.button("Compare with AI", type="primary"):
            with st.spinner(f"Reading the reviews of {name_a} and {name_b}..."):
                try:
                    stats = comparison.stats_text(name_a, metrics_a, name_b, metrics_b, table)
                    store[key] = ai_service.compare_products(reviews_a, name_a, reviews_b, name_b, stats)
                except ai_service.AIServiceError as exc:
                    st.error(str(exc))
        if key in store:
            show_ai_result(store[key], pd.concat([reviews_a, reviews_b]))


# ---------------------------------------------------------------- Review cards

CARDS_PER_PAGE = 12


def review_cards(ctx: Context, view: pd.DataFrame) -> None:
    """Reviews as cards in two columns, with praise and complaint highlights, paged."""
    if view.empty:
        st.info("No reviews match these filters.")
        return
    pages = (len(view) - 1) // CARDS_PER_PAGE + 1
    page = 1
    if pages > 1:
        page = st.number_input(f"Page (of {pages})", min_value=1, max_value=pages, value=1, step=1,
                               key="explorer_page", width=160)
    chunk = view.iloc[(page - 1) * CARDS_PER_PAGE: page * CARDS_PER_PAGE]
    clauses = ctx.mentions[ctx.mentions["review_id"].isin(chunk["review_id"])].groupby("review_id").apply(
        lambda g: list(zip(g["clause"], g["polarity"])), include_groups=False)
    videos = added_videos()
    columns = st.columns(2, gap="medium")
    for i, (_, row) in enumerate(chunk.iterrows()):
        found = clauses.get(row["review_id"], [])
        moment = next((m for m in (moment_for(row["review_id"], c, videos) for c, _ in found) if m), None)
        with columns[i % 2]:
            styles.html_block(styles.review_card(row, found, moment, emotion=emotion_label))


# ---------------------------------------------------------------- Feature Wishlist

def wishlist_page(ctx: Context) -> None:
    styles.page_header("Issues", "Feature Wishlist",
                       "What customers ask you to add or change, grouped and ranked by how many reviews ask for it.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews"])
    requests = wishlist.extract_requests(ctx.reviews)
    if requests.empty:
        st.info("No feature requests found in this selection. Requests are sentences like “I wish it had…”, "
                "“please add…”, “it should have…” or “…hona chahiye”.", icon="💡")
        return
    groups = wishlist.group_requests(requests)
    c1, c2, c3 = st.columns(3)
    c1.metric("Distinct wishes", len(groups), border=True)
    c2.metric("Reviews with a request", requests["review_id"].nunique(), border=True)
    c3.metric("Asked for most", f"{groups.iloc[0]['reviews']} reviews", border=True,
              help=groups.iloc[0]["request"])

    styles.section("Most requested", "Similar requests are grouped together. The wording shown is the most common one.")
    top = max(int(groups["reviews"].max()), 1)
    for rank, row in enumerate(groups.head(10).itertuples(), start=1):
        with st.container(border=True):
            left, right = st.columns((0.12, 1), vertical_alignment="center")
            left.markdown(f"<div style='font-size:1.6rem;font-weight:750;opacity:0.5;text-align:center'>#{rank}</div>",
                          unsafe_allow_html=True)
            with right:
                st.markdown(f"**{row.request}**")
                st.progress(row.reviews / top, text=f"{row.reviews} review{'s' if row.reviews != 1 else ''} · "
                                                    f"{', '.join(row.products)} · latest {row.last_date:%d %b %Y}")
                if len(row.examples) > 1:
                    st.caption("Also asked as: " + " · ".join(f"“{e}”" for e in row.examples[1:]))
                st.caption("Reviews: " + ", ".join(row.review_ids[:8]) + (" …" if len(row.review_ids) > 8 else ""))

    with st.container(border=True):
        styles.section("✨ AI wishlist", "The AI reads every review with a request, merges the ones that ask for the "
                                        "same thing, and suggests quick wins.")
        if not ai_service.is_ai_configured():
            st.info(ai_service.NOT_CONFIGURED_MESSAGE, icon="🔑")
        else:
            store = st.session_state.setdefault("ai_results", {})
            key = (ctx.selection_key, "wishlist")
            if key not in store and st.button("Summarise the wishlist with AI", type="primary"):
                with st.spinner("Reading the requests..."):
                    try:
                        store[key] = ai_service.summarise_wishlist(
                            ctx.reviews[ctx.reviews["review_id"].isin(requests["review_id"])], ctx.subject)
                    except ai_service.AIServiceError as exc:
                        st.error(str(exc))
            if key in store:
                show_ai_result(store[key], ctx.reviews)

    with st.expander(f"All {len(requests)} request sentences"):
        st.dataframe(requests.sort_values("review_date", ascending=False), hide_index=True, width="stretch",
                     column_config={"review_id": "ID", "product_name": "Product",
                                    "review_date": st.column_config.DateColumn("Date", format="DD MMM YYYY"),
                                    "rating": st.column_config.NumberColumn("Rating", format="%d ★"),
                                    "request": st.column_config.TextColumn("Request", width="large")})


# ---------------------------------------------------------------- Reply Studio

REPLIES_PER_PAGE = 6
REPLY_FILTERS = {"Negative reviews": lambda df: df[df["sentiment"] == "Negative"],
                 "Rated 1-3 stars": lambda df: df[df["rating"] <= 3],
                 "All reviews": lambda df: df}


def make_reply(row: pd.Series, mentions: pd.DataFrame, tone: str, signature: str, use_ai: bool) -> str:
    if use_ai:
        return ai_service.draft_reply(row["review_text"], row["product_name"], row["rating"], tone, signature)
    found = mentions[mentions["review_id"] == row["review_id"]]
    return replies.template_reply(row["product_name"], found.loc[found["polarity"] == "complaint", "theme"].tolist(),
                                  found.loc[found["polarity"] == "praise", "theme"].tolist(), tone, signature)


def replies_page(ctx: Context) -> None:
    styles.page_header("Issues", "Reply Studio",
                       "Draft a public reply to each unhappy customer. Always read a draft before you post it.",
                       [ctx.subject])
    if ctx.reviews.empty:
        st.warning("No reviews match the current filters.")
        return
    use_ai = ai_service.is_ai_configured()
    c1, c2, c3, c4 = st.columns((1.3, 1.2, 1.2, 1.4))
    tone = c1.segmented_control("Tone", replies.TONES, default="Friendly", key="reply_tone") or "Friendly"
    which = c2.selectbox("Show", list(REPLY_FILTERS), key="reply_filter")
    themes = c3.multiselect("About", sorted(ctx.mentions["theme"].unique()), key="reply_themes",
                            placeholder="Any theme")
    signature = c4.text_input("Sign as", placeholder="e.g. Priya, Customer Care", key="reply_signature")
    st.caption(("✨ Replies are written by " + ai_service.provider_label() + " for each review.") if use_ai else
               "Replies are filled in from templates using the themes found in each review. "
               "Set AI_API_KEY for replies written for each review.")

    view = REPLY_FILTERS[which](ctx.reviews)
    if themes:
        view = view[view["review_id"].isin(ctx.mentions.loc[ctx.mentions["theme"].isin(themes), "review_id"])]
    view = view.sort_values("review_date", ascending=False)
    if view.empty:
        st.success("No reviews need a reply with these filters.", icon="✅")
        return
    pages = (len(view) - 1) // REPLIES_PER_PAGE + 1
    page = st.number_input(f"Page (of {pages}) · {len(view)} reviews", 1, pages, 1, key="reply_page", width=200) \
        if pages > 1 else 1
    chunk = view.iloc[(page - 1) * REPLIES_PER_PAGE: page * REPLIES_PER_PAGE]
    drafts = st.session_state.setdefault("reply_drafts", {})
    draft_key = lambda review_id: (review_id, tone, signature, use_ai)  # noqa: E731

    missing = [row for _, row in chunk.iterrows() if draft_key(row["review_id"]) not in drafts]
    if missing and st.button(f"✍️ Draft replies for all {len(missing)} on this page", type="primary"):
        with st.spinner("Writing replies..."):
            with ThreadPoolExecutor(max_workers=4) as pool:
                futures = {row["review_id"]: pool.submit(make_reply, row, ctx.mentions, tone, signature, use_ai)
                           for row in missing}
            for review_id, future in futures.items():
                try:
                    drafts[draft_key(review_id)] = future.result()
                except ai_service.AIServiceError as exc:
                    st.error(f"{review_id}: {exc}")

    clauses = ctx.mentions[ctx.mentions["review_id"].isin(chunk["review_id"])].groupby("review_id").apply(
        lambda g: list(zip(g["clause"], g["polarity"])), include_groups=False)
    for _, row in chunk.iterrows():
        left, right = st.columns((1, 1), gap="medium")
        with left:
            styles.html_block(styles.review_card(row, clauses.get(row["review_id"], []), emotion=emotion_label))
        with right:
            key = draft_key(row["review_id"])
            if key in drafts:
                st.code(drafts[key], language=None, wrap_lines=True)
                st.caption("Use the copy icon at the top right of the box. Check it before posting.")
            elif st.button("Draft a reply", key=f"draft_{row['review_id']}", icon="✍️"):
                with st.spinner("Writing..."):
                    try:
                        drafts[key] = make_reply(row, ctx.mentions, tone, signature, use_ai)
                        st.rerun()
                    except ai_service.AIServiceError as exc:
                        st.error(str(exc))


def build_insights(ctx: Context) -> Context:
    ctx.insights = key_insights(ctx.reviews, ctx.mentions, ctx.priority) if not ctx.reviews.empty else []
    return ctx
