"""Dashboard pages. Each page function receives a Context with the filtered data and analysis."""

from __future__ import annotations

import hashlib
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field

import pandas as pd
import streamlit as st

import ai_service
import charts
import styles
from fake_risk import DISCLAIMER as RISK_DISCLAIMER
from insights import WEIGHTS, build_stats_context, evidence_for_theme, health_score, key_insights
from retrieval import find_relevant_reviews
from sentiment import sentiment_counts
from themes import theme_summary
from trends import auto_frequency, review_trends, theme_trends


@dataclass
class Context:
    """Everything a page needs, already filtered to the sidebar selection."""
    reviews: pd.DataFrame          # filtered reviews with sentiment, language and risk columns
    mentions: pd.DataFrame         # theme mentions for those reviews
    priority: pd.DataFrame         # issue priority ranking
    spikes: dict                   # spike detection result
    subject: str                   # e.g. "Nimbus ANC Headphones" or "all products"
    source_label: str
    is_sample: bool
    date_label: str
    insights: list = field(default_factory=list)

    @property
    def selection_key(self) -> str:
        """Identifies the current selection so AI results are kept per selection."""
        ids = "|".join(self.reviews["review_id"].astype(str))
        return hashlib.sha1(f"{self.subject}|{ai_service.get_model_name()}|{ids}".encode()).hexdigest()

    def stats(self) -> str:
        monthly = theme_trends(self.mentions, "Monthly")
        if not monthly.empty:
            monthly = monthly.copy()
            monthly.index = monthly.index.strftime("%Y-%m")
        return build_stats_context(self.reviews, self.mentions, self.priority, self.spikes.get("alerts"), monthly)


PAGES: dict = {}  # filled in by app.py so pages can link to each other


# ---------------------------------------------------------------- shared helpers

def link(page: str, label: str, icon: str) -> None:
    """Link to another dashboard page (if navigation has been set up)."""
    if page in PAGES:
        st.page_link(PAGES[page], label=label, icon=icon)


def review_table(df: pd.DataFrame, extra: list[str] | None = None, order: list[str] | None = None) -> None:
    """Consistent, readable review table."""
    columns = order or ["review_id", "review_date", "product_name", "rating", "sentiment", "language",
                        "review_text"] + (extra or [])
    table = df[[c for c in columns if c in df.columns]].copy()
    st.dataframe(
        table, hide_index=True, width="stretch",
        column_config={
            "review_id": st.column_config.TextColumn("ID", width="small"),
            "review_date": st.column_config.DateColumn("Date", format="DD MMM YYYY", width="medium"),
            "product_name": st.column_config.TextColumn("Product"),
            "rating": st.column_config.NumberColumn("Rating", format="%d ★", width="small"),
            "sentiment": st.column_config.TextColumn("Sentiment", width="small"),
            "sentiment_score": st.column_config.NumberColumn("Score", format="%.2f", width="small"),
            "language": st.column_config.TextColumn("Language", width="small"),
            "review_text": st.column_config.TextColumn("Review", width="large"),
            "risk_level": st.column_config.TextColumn("Risk", width="small"),
            "risk_score": st.column_config.ProgressColumn("Risk score", min_value=0, max_value=100, format="%d"),
            "risk_reasons": st.column_config.ListColumn("Why flagged", width="large"),
            "themes": st.column_config.ListColumn("Themes"),
            "relevance": st.column_config.ProgressColumn("Relevance", min_value=0, max_value=1.5, format="%.2f"),
        },
    )


def show_ai_result(result: dict, reviews: pd.DataFrame) -> None:
    """Render an AI answer with its model note, citation check and the cited reviews as evidence."""
    st.markdown(result["text"])
    note = f"AI-generated by `{result['model']}` from {result['reviews_used']} reviews"
    if result["reviews_used"] < result["reviews_total"]:
        note += f" (most recent {result['reviews_used']} of {result['reviews_total']})"
    if result["chunks"] > 1:
        note += f", processed in {result['chunks']} batches"
    st.caption(note + ". Verify important points against the evidence below.")
    if result["unknown_ids"]:
        st.warning("The AI cited review ID(s) that are not in this selection: " + ", ".join(result["unknown_ids"])
                   + ". Treat the related statements with caution.")
    cited = reviews[reviews["review_id"].astype(str).isin(result["cited_ids"])]
    with st.expander(f"Evidence · {len(cited)} cited review(s), checked against the data"):
        if cited.empty:
            st.write("No reviews were cited.")
        else:
            review_table(cited)


def ai_unavailable_note() -> None:
    st.info(ai_service.NOT_CONFIGURED_MESSAGE + " The sections below are computed directly from the data.", icon="🔑")


def theme_quotes(ctx: Context, theme: str, polarity: str, limit: int = 2) -> None:
    for _, row in evidence_for_theme(ctx.mentions, theme, polarity, limit).iterrows():
        styles.quote(row, highlight=row["clause"])


# ---------------------------------------------------------------- Overview

def overview(ctx: Context) -> None:
    df = ctx.reviews
    styles.page_header("Dashboard overview", ctx.subject if ctx.subject != "all products" else "All products",
                       "How customers feel, what they complain about, and what to fix first.",
                       [ctx.date_label, f"{len(df)} reviews", ctx.source_label])
    if df.empty:
        st.warning("No reviews match the current filters.")
        return

    counts = sentiment_counts(df)
    total = len(df)
    # Small trend lines inside the KPI cards (weekly or monthly, depending on the date span).
    trend = review_trends(df, "Monthly" if auto_frequency(df) == "Monthly" else "Weekly")
    trend = trend[trend["reviews"] > 0]
    spark = dict(chart_type="line") if len(trend) >= 3 else {}
    positive_pct = (trend["positive"] / trend["reviews"] * 100).round(1).tolist()

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Reviews analysed", f"{total:,}", border=True,
              **(dict(spark, chart_data=trend["reviews"].tolist(), chart_type="bar") if spark else {}))
    c2.metric("Average rating", f"{df['rating'].mean():.2f} ★", border=True,
              **(dict(spark, chart_data=trend["avg_rating"].tolist()) if spark else {}))
    c3.metric("Positive", f"{counts['Positive'] / total:.0%}", f"{counts['Positive']} reviews",
              delta_color="off", delta_arrow="off", border=True,
              **(dict(spark, chart_data=positive_pct) if spark else {}))
    c4.metric("Negative", f"{counts['Negative'] / total:.0%}", f"{counts['Negative']} reviews",
              delta_color="off", delta_arrow="off", border=True,
              **(dict(spark, chart_data=trend["negative_pct"].tolist()) if spark else {}))
    c5.metric("Health score", f"{health_score(df)}/100", border=True,
              help="50% average rating (scaled 1-5 → 0-1) + 50% net sentiment ((positive − negative) share, scaled to 0-1).")
    if spark:
        st.caption("Mini charts show each metric over time for the selected dates.")

    alerts = ctx.spikes.get("alerts", [])
    if alerts:
        st.space("small")
        cols = st.columns(min(len(alerts), 3))
        for col, alert in zip(cols, alerts[:3]):
            with col:
                styles.alert_card(alert)
        link("trends", label=f"See all {len(alerts)} alert(s) and trends", icon="📈")

    st.space("small")
    left, right = st.columns((1, 1.15), gap="large")
    with left:
        with st.container(border=True):
            styles.section("How customers feel", "VADER sentiment of every review (Hinglish/Hindi supported).")
            st.plotly_chart(charts.sentiment_bars(counts), config={"displayModeBar": False})
            styles.section("Star ratings")
            st.plotly_chart(charts.rating_distribution(df), config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            styles.section("Most important problems", "Ranked by the transparent priority score.")
            if ctx.priority.empty:
                st.write("No complaints detected in this selection.")
            else:
                rows = "".join(
                    styles.issue_row(r.theme, r.level, f"{r.complaint_reviews} complaint reviews · {r.share_pct}% of all · avg {r.avg_rating}★",
                                     charts.LEVEL_COLORS[r.level])
                    for r in ctx.priority.head(5).itertuples()
                )
                styles.html_block(rows)
                top = ctx.priority.iloc[0]
                st.markdown(f"**Example: {top.theme}**")
                theme_quotes(ctx, top.theme, "complaint", 2)
                link("priority", label="Full priority ranking and evidence", icon="🎯")

    left, right = st.columns(2, gap="large")
    with left:
        with st.container(border=True):
            styles.section("What customers love", "Themes most often praised.")
            summary = theme_summary(ctx.mentions, total)
            praised = summary[summary["praise"] >= 2].sort_values("praise", ascending=False).head(3)
            if praised.empty:
                st.write("No recurring praise found.")
            for row in praised.itertuples():
                st.markdown(f"**{row.theme}** · {row.praise} reviews ({row.praise_pct}%)")
                theme_quotes(ctx, row.theme, "praise", 1)
    with right:
        with st.container(border=True):
            styles.section("Key insights", "Computed from the data, each backed by review IDs.")
            for item in [i for i in ctx.insights if i["kind"] != "overview"][:4]:
                styles.insight_card(item["text"], item["kind"], item["evidence"])
            link("ai", label="AI summary & recommendations", icon="✨")

    with st.container(border=True):
        styles.section("AI summary", "Generated from the reviews in this selection.")
        overall_ai_block(ctx, compact=True)


def overall_ai_block(ctx: Context, compact: bool = False) -> None:
    """Overall AI summary with a generate button; shared by Overview and AI Insights."""
    if not ai_service.is_ai_configured():
        st.info(ai_service.NOT_CONFIGURED_MESSAGE, icon="🔑")
        return
    store = st.session_state.setdefault("ai_results", {})
    key = (ctx.selection_key, "overall")
    if key not in store:
        if st.button("Generate AI summary", type="primary", key=f"gen_overall_{compact}"):
            with st.spinner("Reading reviews and writing the summary..."):
                try:
                    store[key] = ai_service.generate_review_summary(ctx.reviews, ctx.subject)
                except ai_service.AIServiceError as exc:
                    st.error(str(exc))
    if key in store:
        show_ai_result(store[key], ctx.reviews)


# ---------------------------------------------------------------- AI Insights

AI_TASKS = {
    "overall": ("Overall Summary", lambda ctx: ai_service.generate_review_summary(ctx.reviews, ctx.subject)),
    "positive": ("Positive Feedback", lambda ctx: ai_service.generate_positive_summary(
        ctx.reviews[ctx.reviews["sentiment"] == "Positive"], ctx.subject)),
    "negative": ("Negative Feedback", lambda ctx: ai_service.generate_negative_summary(
        ctx.reviews[ctx.reviews["sentiment"] == "Negative"], ctx.subject)),
    "insights": ("Insights & Actions", lambda ctx: ai_service.generate_key_insights(ctx.reviews, ctx.subject, ctx.stats())),
}


def run_ai_tasks(ctx: Context, names: list[str]) -> dict[str, str]:
    """Run several AI tasks in parallel threads. Returns {task: error message} for failures."""
    store = st.session_state.setdefault("ai_results", {})
    errors: dict[str, str] = {}
    with ThreadPoolExecutor(max_workers=4) as pool:
        futures = {name: pool.submit(AI_TASKS[name][1], ctx) for name in names}
        for name, future in futures.items():
            try:
                store[(ctx.selection_key, name)] = future.result()
            except ai_service.AIServiceError as exc:
                errors[name] = str(exc)
    return errors


def ai_insights(ctx: Context) -> None:
    styles.page_header("AI analysis", "AI Review Insights",
                       "Summaries, praise, complaints and recommended actions, every point citing real reviews.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews", f"Model: {ai_service.get_model_name()}"])
    if ctx.reviews.empty:
        st.warning("No reviews match the current filters.")
        return
    configured = ai_service.is_ai_configured()
    store = st.session_state.setdefault("ai_results", {})
    missing = [n for n in AI_TASKS if (ctx.selection_key, n) not in store]

    if not configured:
        ai_unavailable_note()
    elif missing:
        if st.button("✨ Generate full AI analysis", type="primary"):
            with st.status("Analysing reviews with AI...", expanded=False) as status:
                errors = run_ai_tasks(ctx, missing)
                if errors:
                    status.update(label="Some AI sections failed", state="error")
                    for name, message in errors.items():
                        st.error(f"{AI_TASKS[name][0]}: {message}")
                else:
                    status.update(label="AI analysis complete", state="complete")
        st.caption("Runs four grounded AI requests in parallel: overall summary, positive feedback, negative feedback, insights & actions.")

    tabs = st.tabs([AI_TASKS[n][0] for n in AI_TASKS])
    for tab, name in zip(tabs, AI_TASKS):
        with tab:
            result = store.get((ctx.selection_key, name))
            if result:
                show_ai_result(result, ctx.reviews)
            elif configured:
                st.caption("Not generated yet. Use the button above.")
            computed_fallback(ctx, name)


def computed_fallback(ctx: Context, name: str) -> None:
    """Data-driven content shown under each AI tab (and instead of it when AI is off)."""
    total = len(ctx.reviews)
    summary = theme_summary(ctx.mentions, total)
    st.divider()
    if name == "overall":
        styles.section("Computed overview")
        for item in ctx.insights[:1]:
            styles.insight_card(item["text"], item["kind"])
    elif name in ("positive", "negative"):
        polarity, column = ("praise", "praise") if name == "positive" else ("complaint", "complaints")
        styles.section("Most mentioned " + ("strengths" if name == "positive" else "problems"),
                       "Computed from theme detection, with real review quotes.")
        top = summary[summary[column] > 0].sort_values(column, ascending=False).head(4)
        if top.empty:
            st.write("Nothing found in this selection.")
        for row in top.itertuples():
            st.markdown(f"**{row.theme}** · {getattr(row, column)} reviews")
            theme_quotes(ctx, row.theme, polarity, 2)
    else:
        styles.section("Computed insights", "Calculated directly from the data, each with evidence review IDs.")
        for item in ctx.insights:
            styles.insight_card(item["text"], item["kind"], item["evidence"])


# ---------------------------------------------------------------- Ask Your Reviews

SUGGESTED_QUESTIONS = [
    "What are the biggest complaints?",
    "What do customers like most?",
    "Why are customers giving low ratings?",
    "Are delivery complaints increasing?",
    "What should the company improve first?",
]


def ask(ctx: Context) -> None:
    styles.page_header("AI analysis", "Ask Your Reviews",
                       "Ask a question in plain English. Answers use only your reviews and computed statistics.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews"])
    if ctx.reviews.empty:
        st.warning("No reviews match the current filters.")
        return
    if not ai_service.is_ai_configured():
        st.info("AI answers need AI_API_KEY. Without it, you will see the most relevant reviews and statistics "
                "for your question instead.", icon="🔑")

    history = st.session_state.setdefault("qa_history", {}).setdefault(ctx.selection_key, [])
    picked = st.pills("Try a question", SUGGESTED_QUESTIONS, key=f"pill_{ctx.selection_key[:8]}_{len(history)}")
    typed = st.chat_input("Ask about your reviews, e.g. “Is battery life a common problem?”")
    question = typed or picked

    for item in history:
        render_qa(item, ctx)
    if question:
        item = answer(ctx, question)
        history.append(item)
        render_qa(item, ctx)
    if history and st.button("Clear conversation", type="tertiary"):
        history.clear()
        st.rerun()


def answer(ctx: Context, question: str) -> dict:
    relevant = find_relevant_reviews(ctx.reviews, question, ctx.mentions, limit=60)
    item = {"question": question, "relevant_ids": relevant["review_id"].astype(str).tolist(), "result": None, "error": None}
    if ai_service.is_ai_configured():
        with st.spinner("Searching reviews and writing an answer..."):
            try:
                item["result"] = ai_service.answer_question(question, relevant, ctx.stats(), ctx.subject)
            except ai_service.AIServiceError as exc:
                item["error"] = str(exc)
    return item


def render_qa(item: dict, ctx: Context) -> None:
    with st.chat_message("user"):
        st.write(item["question"])
    with st.chat_message("assistant", avatar="✨"):
        if item["result"]:
            show_ai_result(item["result"], ctx.reviews)
            return
        if item["error"]:
            st.error(item["error"])
        relevant = ctx.reviews[ctx.reviews["review_id"].astype(str).isin(item["relevant_ids"][:8])]
        st.markdown("**Most relevant reviews** (found by text search; no AI used):")
        for _, row in relevant.iterrows():
            styles.quote(row)
        with st.expander("Statistics for this selection"):
            st.code(ctx.stats(), language=None)


# ---------------------------------------------------------------- Priority Issues

def priority(ctx: Context) -> None:
    styles.page_header("Issues", "Priority Issues",
                       "Which problems matter most, why, and the real reviews behind each one.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews"])
    if ctx.priority.empty:
        st.success("No complaints detected in this selection.")
        return
    with st.expander("How the priority score works"):
        st.markdown(
            f"""
**Priority score (0-100)** = {WEIGHTS['frequency']} × frequency + {WEIGHTS['negativity']} × negativity
+ {WEIGHTS['low_ratings']} × low ratings + {WEIGHTS['recent_rise']} × recent rise

- **Frequency**: share of all reviews complaining about the issue (20% or more = full marks)
- **Negativity**: how negative the complaint sentences are (average VADER score)
- **Low ratings**: share of those complaint reviews rated 1-2 stars
- **Recent rise**: 1 if the complaint rate rose 50%+ recently, 0.5 if it rose, 0 otherwise

Levels need both a score **and** enough evidence, so one complaint is never Critical:
**Critical** ≥ 70 and ≥ 5 reviews · **High** ≥ 50 and ≥ 3 · **Medium** ≥ 30 and ≥ 2 · otherwise **Low**.
"""
        )

    left, right = st.columns((1, 1), gap="large")
    with left:
        with st.container(border=True):
            styles.section("Priority ranking")
            st.plotly_chart(charts.priority_scores(ctx.priority), config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            styles.section("Praise vs complaints by theme", "Number of reviews praising (right) or complaining (left).")
            st.plotly_chart(charts.praise_vs_complaints(theme_summary(ctx.mentions, len(ctx.reviews))),
                            config={"displayModeBar": False})

    table = ctx.priority[["theme", "level", "score", "complaint_reviews", "share_pct", "avg_rating",
                          "recent_rate_pct", "earlier_rate_pct"]]
    st.dataframe(table, hide_index=True, width="stretch", column_config={
        "theme": "Issue", "level": "Priority",
        "score": st.column_config.ProgressColumn("Score", min_value=0, max_value=100, format="%.0f"),
        "complaint_reviews": st.column_config.NumberColumn("Complaint reviews"),
        "share_pct": st.column_config.NumberColumn("% of all reviews", format="%.1f%%"),
        "avg_rating": st.column_config.NumberColumn("Avg rating", format="%.2f ★"),
        "recent_rate_pct": st.column_config.NumberColumn("Recent rate", format="%.1f%%"),
        "earlier_rate_pct": st.column_config.NumberColumn("Earlier rate", format="%.1f%%"),
    })

    styles.section("Evidence by issue", "Real reviews supporting each issue. The highlighted text is what was detected.")
    for row in ctx.priority.itertuples():
        title = f"{row.theme} · {row.level} priority · {row.complaint_reviews} review(s)"
        with st.expander(title, expanded=row.level in ("Critical", "High") and row.Index < 2):
            st.caption(f"Score {row.score} = frequency {row.frequency} · negativity {row.negativity} · "
                       f"low ratings {row.low_ratings} · recent rise {row.recent_rise}")
            if row.complaint_reviews == 1:
                st.caption("Isolated: only one review mentions this, so it is not yet a recurring pattern.")
            theme_quotes(ctx, row.theme, "complaint", 3)
            all_rows = ctx.reviews[ctx.reviews["review_id"].isin(
                ctx.mentions.loc[(ctx.mentions["theme"] == row.theme) & (ctx.mentions["polarity"] == "complaint"), "review_id"])]
            if len(all_rows) > 3 and st.toggle(f"Show all {len(all_rows)} reviews", key=f"all_{row.theme}"):
                review_table(all_rows.sort_values("review_date", ascending=False))


# ---------------------------------------------------------------- Trends & Alerts

def trends(ctx: Context) -> None:
    styles.page_header("Issues", "Trends & Alerts", "How feedback changes over time, and unusual recent spikes.",
                       [ctx.subject, ctx.date_label])
    df = ctx.reviews
    if df.empty:
        st.warning("No reviews match the current filters.")
        return

    styles.section("Spike alerts", "Detected patterns, not confirmed causes. Recent window vs the weeks before it.")
    spikes = ctx.spikes
    if spikes["status"] != "ok":
        st.info(spikes["message"], icon="ℹ️")
    elif not spikes["alerts"]:
        st.success("No unusual spikes detected. " + spikes["message"], icon="✅")
    else:
        st.caption(spikes["message"])
        cols = st.columns(2)
        for i, alert in enumerate(spikes["alerts"]):
            with cols[i % 2]:
                styles.alert_card(alert)

    auto = auto_frequency(df)
    choice = st.segmented_control("Group by", ["Auto", "Daily", "Weekly", "Monthly"], default="Auto",
                                  key="trend_frequency")
    frequency = auto if choice in (None, "Auto") else choice
    trend = review_trends(df, frequency)
    st.caption(f"Grouped {frequency.lower()}.")

    left, right = st.columns(2, gap="large")
    with left:
        with st.container(border=True):
            styles.section("Review volume by sentiment")
            st.plotly_chart(charts.sentiment_volume(trend), config={"displayModeBar": False})
        with st.container(border=True):
            styles.section("Negative reviews (% of period)")
            st.plotly_chart(charts.line_chart(trend, "negative_pct", "Negative %", charts.SENTIMENT_COLORS["Negative"],
                                              [0, 100], "%"), config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            styles.section("Average rating")
            st.plotly_chart(charts.line_chart(trend, "avg_rating", "Average rating", "#2a78d6", [1, 5.2]),
                            config={"displayModeBar": False})
        with st.container(border=True):
            # One level coarser than the other charts: five theme lines per week are too noisy to read.
            theme_frequency = {"Daily": "Weekly", "Weekly": "Monthly", "Monthly": "Monthly"}[frequency]
            styles.section("Complaint themes over time",
                           f"Top 5 themes by complaint volume, grouped {theme_frequency.lower()} for readability.")
            themes_over_time = theme_trends(ctx.mentions, theme_frequency)
            if themes_over_time.empty:
                st.write("No complaints in this selection.")
            else:
                st.plotly_chart(charts.theme_trend_lines(themes_over_time), config={"displayModeBar": False})

    with st.expander("Trend data table"):
        st.dataframe(trend, hide_index=True, width="stretch")


# ---------------------------------------------------------------- Review Integrity

def integrity(ctx: Context) -> None:
    styles.page_header("Trust", "Review Integrity", "Potentially suspicious reviews, with the reasons they were flagged.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews"])
    df = ctx.reviews
    st.warning(f"**{RISK_DISCLAIMER}** Signals such as duplicate text or review bursts can have innocent explanations. "
               "Use this list to decide what to look at more closely, never to accuse customers.", icon="⚠️")
    if df.empty:
        return

    levels = df["risk_level"].value_counts()
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("High risk", int(levels.get("High", 0)), border=True)
    c2.metric("Medium risk", int(levels.get("Medium", 0)), border=True)
    c3.metric("Low risk", int(levels.get("Low", 0)), border=True)
    c4.metric("Near-duplicates", int((df["max_similarity"] >= 0.9).sum()), border=True,
              help="Reviews of similar length with at least 90% text similarity to another review.")

    left, right = st.columns((1, 1.4), gap="large")
    with left:
        with st.container(border=True):
            styles.section("Risk levels")
            st.plotly_chart(charts.risk_levels(df), config={"displayModeBar": False})
    with right:
        with st.container(border=True):
            styles.section("How the risk score works", "Points add up per review (capped at 100).")
            st.markdown("""
| Signal | Points |
|---|---|
| Near-duplicate text (≥ 90% similar) | +40 |
| Very similar text (≥ 75% similar) | +20 |
| Burst of same-rating reviews on one day | +20 |
| Generic text, no product detail | +15 |
| Star rating contradicts text | +15 |
| Promotional phrasing | +10 |
| Excessive "!!!" or capitals | +10 |
| Extreme rating with another signal | +5 |

**High** ≥ 55 · **Medium** ≥ 30 · **Low** < 30
""")

    styles.section("Flagged reviews", "Each row lists every signal that contributed to its score.")
    level_filter = st.pills("Show", ["High", "Medium", "Low"], default=["High", "Medium"], selection_mode="multi",
                            key="risk_filter")
    flagged = df[df["risk_level"].isin(level_filter or [])].sort_values("risk_score", ascending=False)
    st.caption(f"{len(flagged)} review(s)")
    columns = ["review_id", "risk_level", "risk_score", "risk_reasons", "review_text", "rating",
               "review_date", "product_name"]
    review_table(flagged[columns], extra=["risk_level", "risk_score", "risk_reasons"], order=columns)


# ---------------------------------------------------------------- Review Explorer

def explorer(ctx: Context) -> None:
    styles.page_header("Data", "Review Explorer", "Search and filter every review with its analysis.",
                       [ctx.subject, f"{len(ctx.reviews)} reviews"])
    df = ctx.reviews.copy()
    if df.empty:
        st.warning("No reviews match the current filters.")
        return
    theme_lists = ctx.mentions.assign(label=ctx.mentions["theme"] + " (" + ctx.mentions["polarity"] + ")") \
        .groupby("review_id")["label"].apply(list)
    df["themes"] = df["review_id"].map(theme_lists).apply(lambda v: v if isinstance(v, list) else [])

    c1, c2, c3, c4 = st.columns((2.2, 1, 1, 1))
    query = c1.text_input("Search", placeholder="Words, product or review ID, e.g. battery, delivery, D012")
    sentiments = c2.multiselect("Sentiment", ["Positive", "Neutral", "Negative"])
    languages = c3.multiselect("Language", ["English", "Hinglish", "Hindi"])
    risks = c4.multiselect("Risk", ["High", "Medium", "Low"])
    c5, c6 = st.columns((1, 2.2))
    ratings = c5.slider("Rating", 1, 5, (1, 5))
    theme_filter = c6.multiselect("Theme", sorted(ctx.mentions["theme"].unique()))

    view = df[(df["rating"] >= ratings[0]) & (df["rating"] <= ratings[1])]
    if query.strip():
        q = query.strip()
        view = view[view["review_text"].str.contains(q, case=False, regex=False)
                    | view["product_name"].str.contains(q, case=False, regex=False)
                    | view["review_id"].astype(str).str.contains(q, case=False, regex=False)]
    if sentiments:
        view = view[view["sentiment"].isin(sentiments)]
    if languages:
        view = view[view["language"].isin(languages)]
    if risks:
        view = view[view["risk_level"].isin(risks)]
    if theme_filter:
        ids = ctx.mentions.loc[ctx.mentions["theme"].isin(theme_filter), "review_id"]
        view = view[view["review_id"].isin(ids)]

    top_left, top_right = st.columns((3, 1))
    top_left.caption(f"{len(view)} of {len(df)} reviews")
    export = view.drop(columns=["risk_reasons", "themes"]).assign(
        themes=view["themes"].str.join("; "), risk_reasons=view["risk_reasons"].str.join("; "))
    top_right.download_button("Download CSV", export.to_csv(index=False).encode("utf-8"),
                              "productpulse_reviews.csv", "text/csv", width="stretch")
    review_table(view.sort_values("review_date", ascending=False),
                 extra=["sentiment_score", "themes", "risk_level"])

    with st.container(border=True):
        styles.section("Languages", "Detected with a script + vocabulary heuristic.")
        st.plotly_chart(charts.language_mix(df), config={"displayModeBar": False})


def build_insights(ctx: Context) -> Context:
    ctx.insights = key_insights(ctx.reviews, ctx.mentions, ctx.priority) if not ctx.reviews.empty else []
    return ctx
