[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap, sans-serif"
headingFont = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap, sans-serif"
headingFontWeights = [700, 650, 600]
baseRadius = "0.75rem"
buttonRadius = "0.6rem"
showSidebarBorder = true
chartCategoricalColors = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]

[theme.light]
primaryColor = "#2a78d6"
backgroundColor = "#fcfcfb"
secondaryBackgroundColor = "#f3f2ef"
textColor = "#1a1a19"
borderColor = "#e4e3df"

[theme.light.sidebar]
backgroundColor = "#f6f5f2"

[theme.dark]
primaryColor = "#3987e5"
backgroundColor = "#121211"
secondaryBackgroundColor = "#1f1f1d"
textColor = "#f2f2ef"
borderColor = "#2f2f2c"

[theme.dark.sidebar]
backgroundColor = "#181817"
